name: Matrix Configuration

on: 
    [push,workflow_dispatch]

jobs:
    deploy-to-ubuntu:
        runs-on:  ubuntu-latest
        steps: 
        - name: Echo Docker Details
          run: docker info
        
        - name: Run Images
          run: docker run hello-world

    deploy-to-windows:
        runs-on:  windows-latest
        steps: 
        - name: Echo Docker Details
          run: docker info
        
        - name: Run Images
          run: docker run hello-world
        
